### ISSUE TITLE
Local Cache in Container Never Synced with S3 Bucket

### ISSUE THREAD

**Issue by daviddyball** [jenkins-x/bucketrepo#51]
I've deployed `bucketrepo` alongside an S3 Bucket, but no what config settings I try, the [updateCloudStorage](https://github.com/jenkins-x/bucketrepo/blob/master/internal/controller.go#L225) function never gets called and my bucket remains empty forever.

Config:
```
http:
  addr: ':8080'
  username: ''
  password: ''
storage:
  enabled: true
  bucket_url: 's3://my-cache-bucket'
cache:
  base_dir: '/tmp/bucketrepo'
repositories:
- url: https://myorg.jfrog.io/artifactory/maven
  header:
    Authorization: 'Bearer <token>'
```

When I request an artifact I get the following debug logs on the first try:
```
"GetFile, filename: /com/myorg/package1/1/package1-1.pom"
"Read file from cache: /com/myorg/package1/1/package1-1.pom\n"
"Read file from repository: /com/myorg/package1/1/package1-1.pom"
"Trying to download from repository: https://myorg.jfrog.io/artifactory/maven"
"Write file to cache: /com/myorg/package1/1.187/package1-1.pom\n"
"Read file from cache: /com/myorg/package1/1/package1-1.pom\n"
```

Subsequent requests generate the following:
```
"GetFile, filename: /com/myorg/package1/1/package1-1.pom"
"Read file from cache: /com/myorg/package1/1/package1-1.pom\n"
```
There's no mention of the debug line `"Write file to cloud storage: <file>"` which would indicate that it's never trying to take any of the files it pulled from the repo's to the cloud-cache.

Am I misunderstanding something?
